### PR TITLE
Update to react 0.14.8

### PR DESCRIPTION
**Pull request by davesroka**

### CODE REVIEW

**Comment by kentcdodds** [comment]
Hi there! Thanks for the pull request! Do you use this library? If so, would you like commit access? I'm not using it at all....

**Comment by davesroka** [comment]
Yeah, I’m currently using it on a project.  Happy to have commit access if you’re not doing much with it!

-- 
Dave Sroka


On April 4, 2016 at 12:49:02 AM, Kent C. Dodds (notifications@github.com) wrote:

Hi there! Thanks for the pull request! Do you use this library? If so, would you like commit access? I'm not using it at all....

**Comment by kentcdodds** [comment]
Could you get me your npm username so I can let you do releases?

**Comment by davesroka** [comment]
It’s davesroka .  Let me know if you need anything else!

-- 
Dave Sroka
Sent with Airmail

On April 4, 2016 at 12:17:23 PM, Kent C. Dodds (notifications@github.com) wrote:

Could you get me your npm username so I can let you do releases?

**Comment by kentcdodds** [comment]
Alrighty, it's all yours!

**Comment by davesroka** [comment]
If you're not using this guy anymore, have you switched to something else to do dynamic forms, or just not doing much with them anymore?

**Comment by kentcdodds** [comment]
I'm just not doing forms much in my current app. Maybe one day I'll get into it again, but I'll probably evaluate different existing options the community has built. Maybe I'll come back here, but ¯\\\_(ツ)_/¯ we'll see!

**Comment by davesroka** [comment]
Haha, yeah, make sense to me!

**Comment by astrism** [comment]
In angular I was using mainly using formly to create non-dynamic forms, as it was saving time and reducing repetitive markup. When I switched to react, using formly in my non-dynamic react forms just seemed like overkill and obfuscated the end result. I think there is still a need for this in dynamic forms, I'm just not doing any projects in that area right now.

**Comment by davesroka** [comment]
Yeah, I feel you @astrism .  I'm only using it right now because I have a set of dynamically generated form options from a client's api that needs to be rendered with about 30 different configurations of fields in real time.

**Pull request merged**
